services:
  nextcloud:
    image: nextcloud:33.0.4
    restart: unless-stopped
    labels:
      - rclone.storage=storagebox-crypt
      - traefik.http.middlewares.nextcloud-buffering.buffering.maxRequestBodyBytes=0
      - traefik.http.routers.nextcloud.middlewares=nextcloud-buffering
    volumes:
      - nextcloud_data:/var/www/html
      - /media/storagebox-crypt/nextcloud:/mnt/storagebox
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}
      - OVERWRITEPROTOCOL=https
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=1024M

  nextcloud_db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SECRET_PASSWORD_ROOT}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}

volumes:
  nextcloud_data:
  nextcloud_db_data:
