services:
  nextcloud:
    image: nextcloud:32.0.6
    restart: unless-stopped
    labels:
      - rclone.storage=storagebox-crypt
    volumes:
      - nextcloud_data:/var/www/html
      - /media/storagebox-crypt/nextcloud:/mnt/storagebox
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}
      - OVERWRITEPROTOCOL=https

  nextcloud_db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SECRET_PASSWORD_ROOT}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_SECRET_PASSWORD}

volumes:
  nextcloud_data:
  nextcloud_db_data:
