# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  #firefly
  - package-ecosystem: "docker-compose"
    directory: "/projects/firefly"
    schedule:
      interval: "monthly"
  #immich
  - package-ecosystem: "docker-compose"
    directory: "/projects/immich"
    schedule:
      interval: "monthly"
  #it-tools
  - package-ecosystem: "docker-compose"
    directory: "/projects/it-tools"
    schedule:
      interval: "monthly"
  #n8n
  - package-ecosystem: "docker-compose"
    directory: "/projects/n8n"
    schedule:
      interval: "monthly"
  #paperless
  - package-ecosystem: "docker-compose"
    directory: "/projects/paperless"
    schedule:
      interval: "monthly"
  #tandoor
  - package-ecosystem: "docker-compose"
    directory: "/projects/tandoor"
    schedule:
      interval: "monthly"
  #sonarr
  - package-ecosystem: "docker-compose"
    directory: "/projects/sonarr"
    schedule:
      interval: "monthly"
  #radarr
  - package-ecosystem: "docker-compose"
    directory: "/projects/radarr"
    schedule:
      interval: "monthly"
  #jellyseer
  - package-ecosystem: "docker-compose"
    directory: "/projects/jellyseer"
    schedule:
      interval: "monthly"
  #jellyfin
  - package-ecosystem: "docker-compose"
    directory: "/projects/jellyfin"
    schedule:
      interval: "monthly"