services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    environment:
      - TZ=Europe/Berlin
    volumes:
      - config:/config
      - /mnt/seedbox/media/Movies:/home/etron/media/Movies
      - /mnt/seedbox/downloads:/home/etron/downloads
    restart: unless-stopped

volumes:
  config:
