services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.12.3
    restart: always
    labels:
      - rclone.storage=storagebox-crypt
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node
    volumes:
      - /media/storagebox-crypt/paperless/consume:/home/node/paperless/consume:rw
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
