version: '3.8'
services:
  tandoor:
    restart: unless-stopped
    image: vabene1111/recipes:2.6.1
    labels:
      - rclone.storage=storagebox-crypt
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - /media/storagebox-crypt/tandoor/mediafiles:/opt/recipes/mediafiles
    networks:
      - dokploy-network

  db:
    container_name: tandoor_db
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - /media/storagebox-crypt/tandoor/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dokploy-network

volumes:
  staticfiles:

networks:
  dokploy-network:
    external: true
