version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:10
    volumes:
      - config:/config
      - cache:/cache
      - /mnt/seedbox/media:/media
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  config:
  cache:
  media:
